apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  namespace: logiflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      containers:
        - name: graphql-service
          image: adguevara7/graphql-service:v1.0.0 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085 # Puerto donde corre tu servidor Apollo/GraphQL
          
          # Healthcheck
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10

          env:
            - name: PORT
              value: "8085"
            - name: NODE_ENV
              value: "production"

            # --- CONEXIÓN CON OTROS MICROSERVICIOS (Red Interna K8s) ---
            
            # Mapeo: Usuario -> Auth Service
            - name: USUARIO_SERVICE_URL
              value: "http://auth-service"
            
            # Mapeo: Pedido -> Pedidos Service
            - name: PEDIDO_SERVICE_URL
              value: "http://pedidos-service"
            
            # Mapeo: Factura -> Billing Service
            - name: FACTURA_SERVICE_URL
              value: "http://billing-service"
            
            # Mapeo: Fleet -> Fleet Service
            - name: FLEET_SERVICE_URL
              value: "http://fleet-service"

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
# ==============================================================================
# SERVICE: Expone GraphQL internamente
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: logiflow
spec:
  selector:
    app: graphql-service
  ports:
    - protocol: TCP
      port: 80          # Puerto interno del clúster
      targetPort: 8085  # Puerto del contenedor
---
# ==============================================================================
# INGRESS: Acceso directo opcional al servicio GraphQL
# ==============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-service-ingress
  namespace: logiflow
spec:
  rules:
  - host: graphql.logiflow.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graphql-service
            port:
              number: 80